Repository jenkinsci/github-branch-source-plugin, pull requests merged in 2022-05, with the labels that each got.

#532 Don't pull avatar if remote GitHub Enterprise uses private mode.
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
Labels: bug

#454 JENKINS-66401 Use configured GitHub endpoint for default
  src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
  src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
Labels: bug

#538 Update github-app.adoc
  docs/github-app.adoc
Labels: documentation

#514 Ensure that HTTP client can authenticate with proxy
  pom.xml
  src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
Labels: enhancement

#525 Remove `javaLevel`
  Jenkinsfile
Labels: maintenance

#541 bump github-api to support new teams api
  pom.xml
  src/test/resources/api/__files/body-(root)-XwEI7.json
  src/test/resources/api/__files/body-orgs-cloudbeers-teams-justice-league-AHFpl.json
  src/test/resources/api/mappings/mapping-body-orgs-cloudbeers-teams-repo-gOYDg.json
  src/test/resources/api/mappings/mapping-contents-fu-nMBRw.json
Labels: bug, dependencies

#527 [JENKINS-62220] Automatically select `owner` for `GitHubAppCredentials` acc. to context
  pom.xml
  src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubBuildStatusNotification.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMFileSystem.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java
  src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials/help-owner.html
  src/main/resources/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource/config-detail.jelly
  src/test/java/org/jenkinsci/plugins/github_branch_source/GithubAppCredentialsAppInstallationTokenTest.java
Labels: enhancement

#534 Add `ExcludePrivateRepositoriesTrait`
  src/main/java/org/jenkinsci/plugins/github_branch_source/ExcludePrivateRepositoriesTrait.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorContext.java
  src/main/resources/org/jenkinsci/plugins/github_branch_source/ExcludePrivateTrait/config.jelly
  src/main/resources/org/jenkinsci/plugins/github_branch_source/ExcludePrivateTrait/help.html
  src/main/resources/org/jenkinsci/plugins/github_branch_source/Messages.properties
  src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorTest.java
Labels: enhancement

#565 [JENKINS-57023] Switch dep from `workflow-cps-global-lib` to `pipeline-groovy-lib`
  pom.xml
Labels: dependencies
