Repository jenkinsci/github-branch-source-plugin, pull requests merged in 2022-03, with the labels that each got.

#519 [JENKINS-67918] Prevent Potential NPE.
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java
Labels: bug

#528 Adding `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: internal

#529 Don't persist topics twice
  src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigatorContext.java
  src/main/java/org/jenkinsci/plugins/github_branch_source/TopicsTrait.java
Labels: bug

#458 Fix ignore drafts trait for only github sources
  src/main/java/org/jenkinsci/plugins/github_branch_source/IgnoreDraftPullRequestFilterTrait.java
Labels: enhancement
