Repository jenkinsci/github-branch-source-plugin, pull requests merged in 2023-06, with the labels that each got.

#701 Add `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: chore

#702 Allow `$JENKINS_HOME/org.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.cache/` to be overridden
  src/main/java/org/jenkinsci/plugins/github_branch_source/Connector.java
Labels: enhancement

#707 Refresh plugin for June 2023
  pom.xml
  src/test/java/org/jenkinsci/plugins/github_branch_source/EndpointTest.java
Labels: dependencies
