Repository jenkinsci/github-branch-source-plugin, pull requests merged in 2023-09, with the labels that each got.

#724 PCT compatibility with `cloudbees-bitbucket-branch-source`
  .mvn/extensions.xml
  pom.xml
  src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTraitsTest.java
Labels: developer

#722 .editorconfig: fix *.java indentation…
  .editorconfig
Labels: chore

#653 [JENKINS-71849] Allow `NoThrottle` to be used even on github.com
  src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
  src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
Labels: enhancement

#730 Revert "[JENKINS-71849] Allow `NoThrottle` to be used even on github.…
  src/main/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitChecker.java
  src/test/java/org/jenkinsci/plugins/github_branch_source/ApiRateLimitCheckerTest.java
Labels: bug

#732 Removed 1 unnecessary stubbing in GitHubSCMSourceTest.java
  src/test/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSourceTest.java
Labels: test
